In [ ]:
'''head, tail, info, describe, isnull.sum how many values  are 0 in the dataset, duplicated.sum, fillna(mode in categorical data+ordinal, 
mean where outliers are not found, median in case of quartiles, [fillna to be used when in large data only 2-3 data are na, if out of 5000, 
3000 are na missing vslues then we drop the whole column, 60-70% only missing values are dropped])


'''

In [3]:
import pandas as pd
df=pd.read_csv("employee_salary_dataset.csv") #csv/xls

In [4]:
df #gives info about the dataset

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450
5,6,Employee_6,Finance,3,High School,50,Male,Mumbai,65818
6,7,Employee_7,IT,14,PhD,57,Male,Mumbai,70525
7,8,Employee_8,IT,17,PhD,34,Female,Bangalore,44830
8,9,Employee_9,IT,4,Bachelor,53,Male,Hyderabad,42429
9,10,Employee_10,Operations,18,High School,28,Male,Mumbai,31893
10,11,Employee_11,Marketing,8,PhD,43,Male,Delhi,141381
11,12,Employee_12,IT,4,Master,49,Female,Hyderabad,104909
12,13,Employee_13,Operations,2,Master,23,Female,Hyderabad,72333
13,14,Employee_14,Finance,6,Bachelor,27,Male,Delhi,28436
14,15,Employee_15,Marketing,10,PhD,49,Female,Mumbai,99290
15,16,Employee_16,Finance,4,High School,49,Female,Delhi,101213
16,17,Employee_17,Marketing,18,Master,41,Female,Hyderabad,30895
17,18,Employee_18,Operations,12,PhD,51,Female,Chennai,44738
18,19,Employee_19,HR,2,PhD,32,Male,Chennai,55746
19,20,Employee_20,Marketing,10,Bachelor,49,Male,Bangalore,74377
20,21,Employee_21,Finance,4,Master,46,Female,Delhi,73404
21,22,Employee_22,Operations,14,Master,54,Female,Delhi,79045
22,23,Employee_23,Marketing,16,High School,22,Male,Bangalore,122888
23,24,Employee_24,HR,15,Master,48,Male,Bangalore,64790
24,25,Employee_25,HR,8,High School,34,Female,Bangalore,132455
25,26,Employee_26,IT,14,Master,24,Male,Hyderabad,30600
26,27,Employee_27,IT,8,Bachelor,27,Female,Delhi,119660
27,28,Employee_28,Finance,16,Master,29,Female,Hyderabad,118179
28,29,Employee_29,Marketing,13,High School,48,Male,Bangalore,65764
29,30,Employee_30,Marketing,18,High School,30,Male,Delhi,99543
30,31,Employee_31,IT,15,Bachelor,54,Female,Hyderabad,70714
31,32,Employee_32,Marketing,13,Master,45,Female,Hyderabad,81835
32,33,Employee_33,Marketing,9,Master,36,Male,Bangalore,127946
33,34,Employee_34,HR,15,Bachelor,53,Female,Delhi,134616
34,35,Employee_35,IT,13,Master,53,Male,Bangalore,130983
35,36,Employee_36,Operations,1,Master,45,Female,Delhi,98744
36,37,Employee_37,IT,7,High School,33,Male,Chennai,81491
37,38,Employee_38,Operations,9,Master,23,Male,Mumbai,149123
38,39,Employee_39,HR,1,Master,24,Male,Mumbai,43589
39,40,Employee_40,Finance,12,Bachelor,38,Female,Mumbai,68484
40,41,Employee_41,Marketing,8,Bachelor,23,Female,Bangalore,107989
41,42,Employee_42,HR,11,PhD,23,Male,Chennai,61212
42,43,Employee_43,Marketing,19,High School,49,Female,Delhi,68525
43,44,Employee_44,Finance,17,Master,44,Male,Hyderabad,72202
44,45,Employee_45,Finance,8,Master,53,Male,Delhi,57635
45,46,Employee_46,HR,3,PhD,54,Female,Hyderabad,88208
46,47,Employee_47,Finance,3,Master,22,Female,Delhi,58828
47,48,Employee_48,Operations,1,High School,40,Male,Chennai,43711
48,49,Employee_49,Finance,5,PhD,23,Female,Hyderabad,28420
49,50,Employee_50,Marketing,10,High School,47,Female,Bangalore,121752

In [5]:
df.head() #gives first 5 (by default) values

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450

In [6]:
df.tail() #gives last 5 (by default) values

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
45,46,Employee_46,HR,3,PhD,54,Female,Hyderabad,88208
46,47,Employee_47,Finance,3,Master,22,Female,Delhi,58828
47,48,Employee_48,Operations,1,High School,40,Male,Chennai,43711
48,49,Employee_49,Finance,5,PhD,23,Female,Hyderabad,28420
49,50,Employee_50,Marketing,10,High School,47,Female,Bangalore,121752

In [7]:
df.info() #gives information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EmployeeID        50 non-null     int64
 1   Name              50 non-null     object
 2   Department        50 non-null     object
 3   Experience_Years  50 non-null     int64
 4   Education_Level   50 non-null     object
 5   Age               50 non-null     int64
 6   Gender            50 non-null     object
 7   City              50 non-null     object
 8   Monthly_Salary    50 non-null     int64
dtypes: int64(4), object(5)
memory usage: 3.6+ KB

In [8]:
df.describe() #gives the statistical methods applied to the dataset

       EmployeeID  Experience_Years        Age  Monthly_Salary
count    50.00000         50.000000  50.000000         50.0000
mean     25.50000          9.900000  39.760000      82288.8000
std      14.57738          5.349995  11.539745      33521.4379
min       1.00000          1.000000  22.000000      28420.0000
25%      13.25000          5.250000  28.250000      59424.0000
50%      25.50000         10.000000  43.500000      73890.5000
75%      37.75000         14.750000  49.000000     107219.0000
max      50.00000         19.000000  57.000000     149123.0000

In [9]:
df.isnull() # gives all values where there are no values

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False,False,False
46,False,False,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False,False,False

In [11]:
df.isnull().sum() #gives the sum of count of where values are null

EmployeeID          0
Name                0
Department          0
Experience_Years    0
Education_Level     0
Age                 0
Gender              0
City                0
Monthly_Salary      0
dtype: int64

In [12]:
df.duplicated().sum() #no of values where the data is same

np.int64(0)

In [14]:
df.fillna(80) #fills the space where the values are null

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450
5,6,Employee_6,Finance,3,High School,50,Male,Mumbai,65818
6,7,Employee_7,IT,14,PhD,57,Male,Mumbai,70525
7,8,Employee_8,IT,17,PhD,34,Female,Bangalore,44830
8,9,Employee_9,IT,4,Bachelor,53,Male,Hyderabad,42429
9,10,Employee_10,Operations,18,High School,28,Male,Mumbai,31893
10,11,Employee_11,Marketing,8,PhD,43,Male,Delhi,141381
11,12,Employee_12,IT,4,Master,49,Female,Hyderabad,104909
12,13,Employee_13,Operations,2,Master,23,Female,Hyderabad,72333
13,14,Employee_14,Finance,6,Bachelor,27,Male,Delhi,28436
14,15,Employee_15,Marketing,10,PhD,49,Female,Mumbai,99290
15,16,Employee_16,Finance,4,High School,49,Female,Delhi,101213
16,17,Employee_17,Marketing,18,Master,41,Female,Hyderabad,30895
17,18,Employee_18,Operations,12,PhD,51,Female,Chennai,44738
18,19,Employee_19,HR,2,PhD,32,Male,Chennai,55746
19,20,Employee_20,Marketing,10,Bachelor,49,Male,Bangalore,74377
20,21,Employee_21,Finance,4,Master,46,Female,Delhi,73404
21,22,Employee_22,Operations,14,Master,54,Female,Delhi,79045
22,23,Employee_23,Marketing,16,High School,22,Male,Bangalore,122888
23,24,Employee_24,HR,15,Master,48,Male,Bangalore,64790
24,25,Employee_25,HR,8,High School,34,Female,Bangalore,132455
25,26,Employee_26,IT,14,Master,24,Male,Hyderabad,30600
26,27,Employee_27,IT,8,Bachelor,27,Female,Delhi,119660
27,28,Employee_28,Finance,16,Master,29,Female,Hyderabad,118179
28,29,Employee_29,Marketing,13,High School,48,Male,Bangalore,65764
29,30,Employee_30,Marketing,18,High School,30,Male,Delhi,99543
30,31,Employee_31,IT,15,Bachelor,54,Female,Hyderabad,70714
31,32,Employee_32,Marketing,13,Master,45,Female,Hyderabad,81835
32,33,Employee_33,Marketing,9,Master,36,Male,Bangalore,127946
33,34,Employee_34,HR,15,Bachelor,53,Female,Delhi,134616
34,35,Employee_35,IT,13,Master,53,Male,Bangalore,130983
35,36,Employee_36,Operations,1,Master,45,Female,Delhi,98744
36,37,Employee_37,IT,7,High School,33,Male,Chennai,81491
37,38,Employee_38,Operations,9,Master,23,Male,Mumbai,149123
38,39,Employee_39,HR,1,Master,24,Male,Mumbai,43589
39,40,Employee_40,Finance,12,Bachelor,38,Female,Mumbai,68484
40,41,Employee_41,Marketing,8,Bachelor,23,Female,Bangalore,107989
41,42,Employee_42,HR,11,PhD,23,Male,Chennai,61212
42,43,Employee_43,Marketing,19,High School,49,Female,Delhi,68525
43,44,Employee_44,Finance,17,Master,44,Male,Hyderabad,72202
44,45,Employee_45,Finance,8,Master,53,Male,Delhi,57635
45,46,Employee_46,HR,3,PhD,54,Female,Hyderabad,88208
46,47,Employee_47,Finance,3,Master,22,Female,Delhi,58828
47,48,Employee_48,Operations,1,High School,40,Male,Chennai,43711
48,49,Employee_49,Finance,5,PhD,23,Female,Hyderabad,28420
49,50,Employee_50,Marketing,10,High School,47,Female,Bangalore,121752

In [ ]:
''' uploading and saving the data
uploading: csv, excel, html, json, sql
saving: csv, excel, json, sql
saving a self made data in laptop: df.to_csv

'''

In [ ]:
'''POWER BI
dashboard: 

card: only numeric data
slicer: 


'''